on:
  schedule:
    - cron: "40 20 * * *"
  workflow_dispatch:

jobs:
  scheduled-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Informações do Schedule
        run: |
          echo "Este workflow foi acionado por um evento de agendamento (cron) ou manualmente (workflow_dispatch)."
          echo "Data e hora do acionamento: $(date)"
          echo "Evento de acionamento: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"
          echo "Repositório: ${{ github.repository }}"
          echo "Número do workflow: ${{ github.run_number }}"
          echo "ID do workflow: ${{ github.workflow }}"
          echo "URL do workflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Relatório de execução
        run: |
          echo "Relatório de execução do workflow:"
          echo "Evento: ${{ github.event_name }}"
          echo "Data e hora: $(date)"
          echo "Branch: ${{ github.ref }}"
          echo "Repositório: ${{ github.repository }}"
          echo "Número do workflow: ${{ github.run_number }}"
          echo "ID do workflow: ${{ github.workflow }}"
          echo "URL do workflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
